[package]
name = "sloppy"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libc = "0.2.139"
once_cell = "1.17.1"
os_socketaddr = "0.2.4"

[lib]
name = "sloppy"
crate-type = ["cdylib"]
